# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ESA SNAP LEVEL 1 iCOR.py
# Created on: 2018-05-16 16:36:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from matplotlib import pylab as plt

arcpy.env.workspace = 'F:/ArcGIS/Additional_Thesis'

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
LC08_B04_iCOR_3_tif = "F:/SNAP/iCOR/Landsat 8/LC08_B04_iCOR_3.tif"
LC08_B05_iCOR_3_tif = "F:/SNAP/iCOR/Landsat 8/LC08_B05_iCOR_3.tif"
griddedpoints_l8_maize_30m_shp = "F:/ArcGIS/Additional_Thesis/Geometries/griddedpoints_l8_maize_30m.shp"
S2A_Mosaic_B04_iCOR_30m_collocate2_tif = "F:/SNAP/iCOR/Sentinel 2/Mosaic/Collocate to L8/S2A_Mosaic_B04_iCOR_30m_collocate2.tif"
S2A_Mosaic_B8a_iCOR_30m_collocate2_tif = "F:/SNAP/iCOR/Sentinel 2/Mosaic/Collocate to L8/S2A_Mosaic_B8a_iCOR_30m_collocate2.tif"
S2A_Mosaic_NDVI_iCOR_30m_collocate_tif = "F:/SNAP/iCOR/Sentinel 2/Mosaic/Collocate to L8/NDVI/S2A_Mosaic_NDVI_iCOR_30m_collocate.tif"
LC08_NDVI_iCOR_3_tif = "F:/SNAP/iCOR/Landsat 8/NDVI/LC08_NDVI_iCOR_3.tif"

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(Float(\"%S2A_Mosaic_B8a_iCOR_30m_collocate2.tif%\") - Float(\"%S2A_Mosaic_B04_iCOR_30m_collocate2.tif%\")) / (Float(\"%S2A_Mosaic_B8a_iCOR_30m_collocate2.tif%\") + Float(\"%S2A_Mosaic_B04_iCOR_30m_collocate2.tif%\"))", S2A_Mosaic_NDVI_iCOR_30m_collocate_tif)

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(Float(\"%LC08_B05_iCOR_3.tif%\") - Float(\"%LC08_B04_iCOR_3.tif%\")) / (Float(\"%LC08_B05_iCOR_3.tif%\") + Float(\"%LC08_B04_iCOR_3.tif%\"))", LC08_NDVI_iCOR_3_tif)

# Process: Extract Multi Values to Points
arcpy.gp.ExtractMultiValuesToPoints_sa(griddedpoints_l8_maize_30m_shp, "'F:/SNAP/iCOR/Sentinel 2/Mosaic/Collocate to L8/NDVI/S2A_Mosaic_NDVI_iCOR_30m_collocate.tif' S2A_Mosa_1;'F:/SNAP/iCOR/Landsat 8/NDVI/LC08_NDVI_iCOR_3.tif' LC08_NDVI1", "NONE")

fc = 'F:/ArcGIS/Additional_Thesis/Geometries/griddedpoints_l8_maize_30m.shp'
field1 = 'S2A_Mosaic'
field2 = 'LC08_NDVI_'

# Do things on point shapefile
cursor = arcpy.SearchCursor(fc, fields= field1 + ';' + field2)

# Initialize
S2 = []
L8 = []

# open txt file to write the outputs
f = open('F:/SNAP/iCOR/Sentinel 2/Mosaic/Collocate to L8/NDVI/S2A_Mosaic_NDVI_iCOR_30m_collocate.txt', 'w')

# parse every row and write it to a list (for S2 and L8)
for i, row in enumerate(cursor):
    S2.append(row.getValue(field1))
    L8.append(row.getValue(field2))
	
	# Write outputs
    f.write('{0},{1}'.format(S2[i], L8[i]))

# Close txt file
f.close()
# Write txt file



# Plot
plt.figure()
plt.scatter(S2, L8, marker='.')
plt.axis('tight')
plt.xlabel('Sentinel 2')
plt.ylabel('Landsat 8')
plt.title('NDVI iCOR')
plt.show()