# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Br_T_LAI_to_LST.py
# Created on: 2020-10-30 17:00:36.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
RT_LC08_L1TP_191029_20170620_20170630_01_T1_B10_TIF = "RT_LC08_L1TP_191029_20170620_20170630_01_T1_B10.TIF"
MOSES_LAI_L8_tif__2_ = "MOSES_LAI_L8.tif"
b10_emissivity_tif = "F:\\ArcGIS\\Additional_Thesis\\Miscellaneous\\b10_emissivity.tif"
LST_LC08_tif = "F:\\ArcGIS\\Additional_Thesis\\Miscellaneous\\LST_LC08.tif"
MOSES_LAI_L8_tif__3_ = "MOSES_LAI_L8.tif"
MOSES_LAI_L8_tif__4_ = "MOSES_LAI_L8.tif"

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("Con(\"%MOSES_LAI_L8.tif (2)%\" <= 3, 0.95 + 0.01*\"%MOSES_LAI_L8.tif (2)%\", Con(\"%MOSES_LAI_L8.tif (2)%\" > 3, 0.98))", b10_emissivity_tif)

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("\"%RT_LC08_L1TP_191029_20170620_20170630_01_T1_B10.TIF%\" / (1 + (10.895 * \"%RT_LC08_L1TP_191029_20170620_20170630_01_T1_B10.TIF%\" / 14388) * Ln(\"%b10_emissivity.tif%\")) - 273.15", LST_LC08_tif)

