# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Compute_CSI_Corrected.py
# Created on: 2020-10-30 17:01:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
LST_LC08_tif = "LST_LC08.tif"
LC08_NDVI_iCOR_3_tif = "LC08_NDVI_iCOR_3.tif"
AirTemperature_30m_tif = "AirTemperature_30m.tif"
VPD_kPa_30m_tif = "VPD_kPa_30m.tif"
CSI_LC08_DeltaCorrected_tif = "F:\\ArcGIS\\Additional_Thesis\\Miscellaneous\\CSI_LC08_DeltaCorrected.tif"

# Process: Raster Calculator
tempEnvironment0 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = "PROJCS['WGS_1984_UTM_Zone_33N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',15.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]"
tempEnvironment1 = arcpy.env.resamplingMethod
arcpy.env.resamplingMethod = "NEAREST"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "30"
arcpy.gp.RasterCalculator_sa("((\"%LST_LC08.tif%\" - 28.4 * Exp( - 3.6 * \"%LC08_NDVI_iCOR_3.tif%\")) - \"%AirTemperature_30m.tif%\") / \"%VPD_kPa_30m.tif%\"", CSI_LC08_DeltaCorrected_tif)
arcpy.env.outputCoordinateSystem = tempEnvironment0
arcpy.env.resamplingMethod = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2

