# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# DEM_Slope.py
# Created on: 2020-10-30 17:02:01.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
n44_e011_1arc_v3_tif = "F:\\ArcGIS\\Additional_Thesis\\DEM\\n44_e011_1arc_v3.tif"
dem_proj2_tif = "F:\\ArcGIS\\Additional_Thesis\\DEM\\dem_proj2.tif"
slope2_tif = "F:\\ArcGIS\\Additional_Thesis\\DEM\\slope2.tif"
slope_tif__3_ = slope2_tif
n43_e012_1arc_v3_tif = "F:\\ArcGIS\\Additional_Thesis\\DEM\\n43_e012_1arc_v3.tif"
dem_proj3_tif = "F:\\ArcGIS\\Additional_Thesis\\DEM\\dem_proj3.tif"
slope3_tif = "F:\\ArcGIS\\Additional_Thesis\\DEM\\slope3.tif"
slope_tif__2_ = "F:\\ArcGIS\\Additional_Thesis\\DEM\\slope.tif"
AreaOfInterest = "AreaOfInterest"
slope_Clip = "C:\\Users\\KostaGeo\\Documents\\ArcGIS\\Default.gdb\\slope_Clip"

# Process: Project Raster
arcpy.ProjectRaster_management(n44_e011_1arc_v3_tif, dem_proj2_tif, "PROJCS['WGS_1984_UTM_Zone_33N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',15.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "NEAREST", "27,282855144685 27,282855144685", "", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Slope
arcpy.gp.Slope_sa(dem_proj2_tif, slope2_tif, "DEGREE", "1")

# Process: Project Raster (2)
arcpy.ProjectRaster_management(n43_e012_1arc_v3_tif, dem_proj3_tif, "PROJCS['WGS_1984_UTM_Zone_33N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',15.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "NEAREST", "27,1516815536251 27,1516815536251", "", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Slope (2)
arcpy.gp.Slope_sa(dem_proj3_tif, slope3_tif, "DEGREE", "1")

# Process: Mosaic
arcpy.Mosaic_management("F:\\ArcGIS\\Additional_Thesis\\DEM\\slope2.tif;F:\\ArcGIS\\Additional_Thesis\\DEM\\slope3.tif", slope_tif__2_, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Clip
arcpy.Clip_management(slope_tif__3_, "249181,910361208 4862562,01955873 324454,679739524 4935261,28542575", slope_Clip, AreaOfInterest, "-3.402823e+038", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

