# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Eo_Maize.py
# Created on: 2020-10-30 17:02:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
ET0pm_clip3_Resample_tif = "F:\\ArcGIS\\Additional_Thesis\\Miscellaneous\\ET0pm_clip3_Resample.tif"
Maize_within_Eo_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\Maize_within_Eo.shp"
ET0pm_clip3_Resample_Maize_tif = "F:\\ArcGIS\\Additional_Thesis\\Miscellaneous\\ET0pm_clip3_Resample_Maize.tif"

# Process: Clip
arcpy.Clip_management(ET0pm_clip3_Resample_tif, "731960 4868700 800660 4933666,77474976", ET0pm_clip3_Resample_Maize_tif, Maize_within_Eo_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

