# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ESA_SNAP_Level_1.py
# Created on: 2020-10-30 17:03:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
griddedpoints_s2_maize_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_s2_maize.shp"
griddedpoints_s2_maize_shp__3_ = griddedpoints_s2_maize_shp
L8_B5_RectClip_collocate10m_tif = "F:\\SNAP\\Landsat 8\\L8_B5_RectClip_collocate10m.tif"
L8_B4_RectClip_collocate10m_tif = "F:\\SNAP\\Landsat 8\\L8_B4_RectClip_collocate10m.tif"
L8L1_RectClip_collocate_NDVI_10m_tif = "F:\\SNAP\\NDVI\\L8L1_RectClip_collocate_NDVI_10m.tif"
S2L1_QPMosaic_RectClip_NDVI_tif__2_ = "F:\\SNAP\\NDVI\\S2L1_QPMosaic_RectClip_NDVI.tif"
S2L1_L8L1_collocate_NDVI_Difference_tif = "F:\\SNAP\\NDVI\\S2L1_L8L1_collocate_NDVI_Difference.tif"
L8_B5_RectClip_tif = "F:\\SNAP\\Landsat 8\\L8_B5_RectClip.tif"
L8_B4_RectClip_tif = "F:\\SNAP\\Landsat 8\\L8_B4_RectClip.tif"
L8L1_RectClip_NDVI_tif = "F:\\SNAP\\NDVI\\L8L1_RectClip_NDVI.tif"
Maize_within_Eo_L8CRS_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\Maize_within_Eo_L8CRS.shp"
L8L1_RectClip_NDVI_Clip = "C:\\Users\\KostaGeo\\Documents\\ArcGIS\\Default.gdb\\L8L1_RectClip_NDVI_Clip"
griddedpoints_L8_maize_30m_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_L8_maize_30m.shp"
RasterT_L8L1_Re1__2_ = griddedpoints_L8_maize_30m_shp
QPMosaic_B8a_RectClip_20m_collocate_tif = "F:\\SNAP\\Sentinel 2\\Landsat CRS\\QPMosaic_B8a_RectClip_20m_collocate.tif"
QPMosaic_B4_RectClip_collocate_tif = "F:\\SNAP\\Sentinel 2\\Landsat CRS\\QPMosaic_B4_RectClip_collocate.tif"
S2L1_RectClip_collocate_NDVI_tif = "F:\\SNAP\\NDVI\\S2L1_RectClip_collocate_NDVI.tif"

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(Float(\"%L8_B5_RectClip_collocate10m.tif%\") - Float(\"%L8_B4_RectClip_collocate10m.tif%\")) / (Float(\"%L8_B5_RectClip_collocate10m.tif%\") + Float(\"%L8_B4_RectClip_collocate10m.tif%\"))", L8L1_RectClip_collocate_NDVI_10m_tif)

# Process: Extract Multi Values to Points
arcpy.gp.ExtractMultiValuesToPoints_sa(griddedpoints_s2_maize_shp, "F:\\SNAP\\NDVI\\L8L1_RectClip_collocate_NDVI_10m.tif L8L1_Rec_1;F:\\SNAP\\NDVI\\S2L1_QPMosaic_RectClip_NDVI.tif S2L1_QPMos", "NONE")

# Process: Raster Calculator (3)
arcpy.gp.RasterCalculator_sa("Abs(\"%S2L1_QPMosaic_RectClip_NDVI.tif (2)%\" - \"%L8L1_RectClip_collocate_NDVI_10m.tif%\")", S2L1_L8L1_collocate_NDVI_Difference_tif)

# Process: Raster Calculator (4)
arcpy.gp.RasterCalculator_sa("(Float(\"%L8_B5_RectClip.tif%\") - Float(\"%L8_B4_RectClip.tif%\")) / (Float(\"%L8_B5_RectClip.tif%\") + Float(\"%L8_B4_RectClip.tif%\"))", L8L1_RectClip_NDVI_tif)

# Process: Clip
arcpy.Clip_management(L8L1_RectClip_NDVI_tif, "252883,672118938 4864945,54287185 319198,220048529 4932464,52581433", L8L1_RectClip_NDVI_Clip, Maize_within_Eo_L8CRS_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster to Point
arcpy.RasterToPoint_conversion(L8L1_RectClip_NDVI_Clip, griddedpoints_L8_maize_30m_shp, "Value")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(Float(\"%QPMosaic_B8a_RectClip_20m_collocate.tif%\") - Float(\"%QPMosaic_B4_RectClip_collocate.tif%\")) / (Float(\"%QPMosaic_B8a_RectClip_20m_collocate.tif%\") + Float(\"%QPMosaic_B4_RectClip_collocate.tif%\"))", S2L1_RectClip_collocate_NDVI_tif)

# Process: Extract Multi Values to Points (2)
arcpy.gp.ExtractMultiValuesToPoints_sa(griddedpoints_L8_maize_30m_shp, "F:\\SNAP\\NDVI\\S2L1_RectClip_collocate_NDVI.tif S2L1_Rec_1;F:\\SNAP\\NDVI\\L8L1_RectClip_NDVI.tif L8L1_Rec_1", "NONE")

