# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ESA_SNAP_Level_2.py
# Created on: 2020-10-30 17:03:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
griddedpoints_l8_maize_30m_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_l8_maize_30m.shp"
griddedpoints_l8_maize_30m_shp__2_ = griddedpoints_l8_maize_30m_shp
L8_B5_RectClip_tif = "F:\\SNAP\\Level 2\\Landsat 8\\L8_B5_RectClip.tif"
L8_B4_RectClip_tif = "F:\\SNAP\\Level 2\\Landsat 8\\L8_B4_RectClip.tif"
L8L2_RectClip_NDVI_tif = "F:\\SNAP\\Level 2\\NDVI\\L8L2_RectClip_NDVI.tif"
QPB8AClip1_collocate_tif = "F:\\SNAP\\Level 2\\Sentinel 2\\QPB8AClip1_collocate.tif"
QPB04Clip1_collocate_tif = "F:\\SNAP\\Level 2\\Sentinel 2\\QPB04Clip1_collocate.tif"
S2L2_QPClip1_collocate_NDVI_30m_tif = "F:\\SNAP\\Level 2\\NDVI\\S2L2_QPClip1_collocate_NDVI_30m.tif"

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(Float(\"%L8_B5_RectClip.tif%\") - Float(\"%L8_B4_RectClip.tif%\")) / (Float(\"%L8_B5_RectClip.tif%\") + Float(\"%L8_B4_RectClip.tif%\"))", L8L2_RectClip_NDVI_tif)

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(Float(\"%QPB8AClip1_collocate.tif%\") - Float(\"%QPB04Clip1_collocate.tif%\")) / (Float(\"%QPB8AClip1_collocate.tif%\") + Float(\"%QPB04Clip1_collocate.tif%\"))", S2L2_QPClip1_collocate_NDVI_30m_tif)

# Process: Extract Multi Values to Points
arcpy.gp.ExtractMultiValuesToPoints_sa(griddedpoints_l8_maize_30m_shp, "'F:\\SNAP\\Level 2\\NDVI\\L8L2_RectClip_NDVI.tif' #;'F:\\SNAP\\Level 2\\NDVI\\S2L2_QPClip1_collocate_NDVI_30m.tif' #", "NONE")

