# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ESA_SNAP_Level_1_iCOR.py
# Created on: 2020-10-30 17:03:24.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
LC08_B04_iCOR_3_tif = "F:\\SNAP\\iCOR\\Landsat 8\\LC08_B04_iCOR_3.tif"
LC08_B05_iCOR_3_tif = "F:\\SNAP\\iCOR\\Landsat 8\\LC08_B05_iCOR_3.tif"
griddedpoints_l8_maize_30m_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_l8_maize_30m.shp"
griddedpoints_l8_maize_30m_shp__5_ = griddedpoints_l8_maize_30m_shp
s2a_mosaic_b8a_icor_20m_null_aoi_AROP_30m_asc = "F:\\Virtual Machine\\AROP_Share\\public_AROP_exe_v2.2.9\\s2a_mosaic_b8a_icor_20m_null_aoi_AROP_30m.asc"
s2a_mosaic_b04_icor_10m_null_aoi_AROP_30m_asc = "F:\\Virtual Machine\\AROP_Share\\public_AROP_exe_v2.2.9\\s2a_mosaic_b04_icor_10m_null_aoi_AROP_30m.asc"
S2A_Mosaic_NDVI_iCOR_30m_AROP_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\NDVI\\S2A_Mosaic_NDVI_iCOR_30m_AROP.tif"
lc08_b05_icor_3_null_aoi_asc = "F:\\Virtual Machine\\AROP_Share\\public_AROP_exe_v2.2.9\\lc08_b05_icor_3_null_aoi.asc"
lc08_b04_icor_3_null_aoi_asc = "F:\\Virtual Machine\\AROP_Share\\public_AROP_exe_v2.2.9\\lc08_b04_icor_3_null_aoi.asc"
LC08_NDVI_iCOR_3_AROP_tif = "F:\\SNAP\\iCOR\\Landsat 8\\NDVI\\LC08_NDVI_iCOR_3_AROP.tif"
S2A_Mosaic_B04_iCOR_30m_collocate2_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2A_Mosaic_B04_iCOR_30m_collocate2.tif"
S2A_Mosaic_B8a_iCOR_30m_collocate2_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2A_Mosaic_B8a_iCOR_30m_collocate2.tif"
griddedpoints_l8_maize_30m_shp__3_ = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_l8_maize_30m.shp"
griddedpoints_l8_maize_30m_shp__4_ = griddedpoints_l8_maize_30m_shp__3_
L8L1_RectClip_NDVI_tif = "F:\\SNAP\\NDVI\\L8L1_RectClip_NDVI.tif"
LC08_NDVI_iCOR_3_tif__2_ = "F:\\SNAP\\iCOR\\Landsat 8\\NDVI\\LC08_NDVI_iCOR_3.tif"

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(Float(\"%s2a_mosaic_b8a_icor_20m_null_aoi_AROP_30m.asc%\") - Float(\"%s2a_mosaic_b04_icor_10m_null_aoi_AROP_30m.asc%\")) / (Float(\"%s2a_mosaic_b8a_icor_20m_null_aoi_AROP_30m.asc%\") + Float(\"%s2a_mosaic_b04_icor_10m_null_aoi_AROP_30m.asc%\"))", S2A_Mosaic_NDVI_iCOR_30m_AROP_tif)

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(Float(\"%lc08_b05_icor_3_null_aoi.asc%\") - Float(\"%lc08_b04_icor_3_null_aoi.asc%\")) / (Float(\"%lc08_b05_icor_3_null_aoi.asc%\") + Float(\"%lc08_b04_icor_3_null_aoi.asc%\"))", LC08_NDVI_iCOR_3_AROP_tif)

# Process: Extract Multi Values to Points
arcpy.gp.ExtractMultiValuesToPoints_sa(griddedpoints_l8_maize_30m_shp, "'F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\NDVI\\S2A_Mosaic_NDVI_iCOR_30m_AROP.tif' S2A_NDVI_AROP;'F:\\SNAP\\iCOR\\Landsat 8\\NDVI\\LC08_NDVI_iCOR_3_AROP.tif' LC08_NDVI_AROP", "NONE")

# Process: Extract Multi Values to Points (2)
arcpy.gp.ExtractMultiValuesToPoints_sa(griddedpoints_l8_maize_30m_shp__3_, "F:\\SNAP\\NDVI\\L8L1_RectClip_NDVI.tif L8L1_RectC;'F:\\SNAP\\iCOR\\Landsat 8\\NDVI\\LC08_NDVI_iCOR_3.tif' LC08_NDVI_", "NONE")

