# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Extract_Sentinel_2_iCOR_bands.py
# Created on: 2020-10-30 17:04:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Band_5 = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_20M.tif\\Band_5"
S2A_QP_B11_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QP_B11_iCOR_20m.tif"
S2A_Mosaic_B11_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B11_iCOR_20m.tif"
S2A_Mosaic_B11_iCOR_20m_tif__3_ = S2A_Mosaic_B11_iCOR_20m_tif
Band_5__2_ = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_20M.tif\\Band_5"
S2A_QQ_B11_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_QQ_B11_iCOR_20m.tif"
S2A_Mosaic_B04_iCOR_10m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B04_iCOR_10m.tif"
Band_4 = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_10M.tif\\Band_4"
S2A_QP_B08_iCOR_10m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QP_B08_iCOR_10m.tif"
S2A_Mosaic_B08_iCOR_10m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B08_iCOR_10m.tif"
S2A_Mosaic_B08_iCOR_10m_tif__3_ = S2A_Mosaic_B08_iCOR_10m_tif
Band_4__2_ = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_10M.tif\\Band_4"
S2A_QQ_B08_iCOR_10m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_QQ_B08_iCOR_10m.tif"
Band_1 = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_10M.tif\\Band_1"
S2A_QP_B02_iCOR_10m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QP_B02_iCOR_10m.tif"
S2A_Mosaic_B02_iCOR_10m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B02_iCOR_10m.tif"
S2A_Mosaic_B02_iCOR_10m_tif__3_ = S2A_Mosaic_B02_iCOR_10m_tif
Band_1__2_ = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_10M.tif\\Band_1"
S2A_QQ_B02_iCOR_10m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_QQ_B02_iCOR_10m.tif"
S2A_Moisaic_BareSoilIndex_iCOR_10m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Moisaic_BareSoilIndex_iCOR_10m.tif"

# Process: Composite Bands (3)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_20M.tif\\Band_5'", S2A_QP_B11_iCOR_20m_tif)

# Process: Copy Raster (3)
arcpy.CopyRaster_management(S2A_QP_B11_iCOR_20m_tif, S2A_Mosaic_B11_iCOR_20m_tif, "", "", "", "NONE", "NONE", "", "NONE", "NONE", "", "NONE")

# Process: Composite Bands (6)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_20M.tif\\Band_5'", S2A_QQ_B11_iCOR_20m_tif)

# Process: Mosaic (3)
arcpy.Mosaic_management("'F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B11_iCOR_20m.tif';'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_QQ_B11_iCOR_20m.tif'", S2A_Mosaic_B11_iCOR_20m_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Composite Bands (2)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_10M.tif\\Band_4'", S2A_QP_B08_iCOR_10m_tif)

# Process: Copy Raster (2)
arcpy.CopyRaster_management(S2A_QP_B08_iCOR_10m_tif, S2A_Mosaic_B08_iCOR_10m_tif, "", "", "", "NONE", "NONE", "", "NONE", "NONE", "", "NONE")

# Process: Composite Bands (5)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_10M.tif\\Band_4'", S2A_QQ_B08_iCOR_10m_tif)

# Process: Mosaic (2)
arcpy.Mosaic_management("'F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B08_iCOR_10m.tif';'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_QQ_B08_iCOR_10m.tif'", S2A_Mosaic_B08_iCOR_10m_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Composite Bands
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_10M.tif\\Band_1'", S2A_QP_B02_iCOR_10m_tif)

# Process: Copy Raster
arcpy.CopyRaster_management(S2A_QP_B02_iCOR_10m_tif, S2A_Mosaic_B02_iCOR_10m_tif, "", "", "", "NONE", "NONE", "", "NONE", "NONE", "", "NONE")

# Process: Composite Bands (4)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_10M.tif\\Band_1'", S2A_QQ_B02_iCOR_10m_tif)

# Process: Mosaic
arcpy.Mosaic_management("'F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B02_iCOR_10m.tif';'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_QQ_B02_iCOR_10m.tif'", S2A_Mosaic_B02_iCOR_10m_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Raster Calculator
tempEnvironment0 = arcpy.env.resamplingMethod
arcpy.env.resamplingMethod = "NEAREST"
tempEnvironment1 = arcpy.env.cellSize
arcpy.env.cellSize = "MINOF"
arcpy.gp.RasterCalculator_sa("((\"%S2A_Mosaic_B11_iCOR_20m.tif (3)%\" + \"%S2A_Mosaic_B04_iCOR_10m.tif%\") - (\"%S2A_Mosaic_B08_iCOR_10m.tif (3)%\" + \"%S2A_Mosaic_B02_iCOR_10m.tif (3)%\")) / ((\"%S2A_Mosaic_B11_iCOR_20m.tif (3)%\" + \"%S2A_Mosaic_B04_iCOR_10m.tif%\") + (\"%S2A_Mosaic_B08_iCOR_10m.tif (3)%\" + \"%S2A_Mosaic_B02_iCOR_10m.tif (3)%\"))", S2A_Moisaic_BareSoilIndex_iCOR_10m_tif)
arcpy.env.resamplingMethod = tempEnvironment0
arcpy.env.cellSize = tempEnvironment1

