# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Extract_values_from_Biophysical.py
# Created on: 2020-10-30 17:04:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
griddedpoints_l8_maize_30m_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_l8_maize_30m.shp"
griddedpoints_l8_maize_30m_shp__2_ = griddedpoints_l8_maize_30m_shp
Albedo_171_S2_collocate_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\Albedo_171_S2_collocate.tif"
Albedo_171_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\Albedo_171.tif"
h_c_2_171_S2_collocate_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\h_c_2_171_S2_collocate.tif"
h_c_2_171_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\h_c_2_171.tif"
MOSE_CWD_AN_S2_collocate_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSE_CWD_AN_S2_collocate.tif"
MOSES_CWD_AN_20170619_L8_2017171_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_CWD_AN_20170619_L8_2017171.tif"
MOSE_CWD_EMP_S2_collocate_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSE_CWD_EMP_S2_collocate.tif"
MOSES_CWD_EMP_20170619_L8_2017171_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_CWD_EMP_20170619_L8_2017171.tif"
MOSES_Kc_AN_S2_collocate_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSES_Kc_AN_S2_collocate.tif"
MOSES_Kc_AN_20170619_L8_2017171_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_Kc_AN_20170619_L8_2017171.tif"
MOSES_Kc_NDVI_S2_collocate_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSES_Kc_NDVI_S2_collocate.tif"
MOSES_Kc_NDVI_20170619_L8_2017171_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_Kc_NDVI_20170619_L8_2017171.tif"
MOSES_LAI_20170420_S2_collocate_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSES_LAI_20170420_S2_collocate.tif"
MOSES_LAI_20170619_L8_2017171_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_LAI_20170619_L8_2017171.tif"

# Process: Extract Multi Values to Points
arcpy.gp.ExtractMultiValuesToPoints_sa(griddedpoints_l8_maize_30m_shp, "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\Albedo_171_S2_collocate.tif Albedo_;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\Albedo_171.tif Albedo_171;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\h_c_2_171_S2_collocate.tif h_c_2_1;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\h_c_2_171.tif h_c_2_171;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSE_CWD_AN_S2_collocate.tif MOSE_CW;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_CWD_AN_20170619_L8_2017171.tif MOSES_CWD_;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSE_CWD_EMP_S2_collocate.tif MOSE__1;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_CWD_EMP_20170619_L8_2017171.tif MOSES_CWD1;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSES_Kc_AN_S2_collocate.tif MOSES_K;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_Kc_AN_20170619_L8_2017171.tif MOSES_Kc_A;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSES_Kc_NDVI_S2_collocate.tif MOSES_1;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_Kc_NDVI_20170619_L8_2017171.tif MOSES_Kc_N;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\S2\\collocate\\MOSES_LAI_20170420_S2_collocate.tif MOSES_L;F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\L8\\MOSES_LAI_20170619_L8_2017171.tif MOSES_LAI_", "NONE")

