# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# L8_L2A.py
# Created on: 2020-10-30 17:05:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
LC08_L1TP_191029_20170620_20170630_01_T1_sr_band4_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\LC081910292017062001T1-SC20180223140052\\LC08_L1TP_191029_20170620_20170630_01_T1_sr_band4.tif"
et0pm_polygDiss_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\et0pm_polygDiss.shp"
L8L2A_B4clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\Clipped\\L8L2A_B4clip1.tif"
LC08_L1TP_191029_20170620_20170630_01_T1_sr_band5_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\LC081910292017062001T1-SC20180223140052\\LC08_L1TP_191029_20170620_20170630_01_T1_sr_band5.tif"
L8L2A_B5clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\Clipped\\L8L2A_B5clip1.tif"
L8L2A_Stack_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\Stacks\\L8L2A_Stack.tif"

# Process: Clip (2)
arcpy.Clip_management(LC08_L1TP_191029_20170620_20170630_01_T1_sr_band4_tif, "249659,201223261 4863256,07549126 323788,779942527 4935084,67478671", L8L2A_B4clip1_tif, et0pm_polygDiss_shp, "-9999", "NONE", "NO_MAINTAIN_EXTENT")

# Process: Clip
arcpy.Clip_management(LC08_L1TP_191029_20170620_20170630_01_T1_sr_band5_tif, "249659,201223261 4863256,07549126 323788,779942527 4935084,67478671", L8L2A_B5clip1_tif, et0pm_polygDiss_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Composite Bands
arcpy.CompositeBands_management("'F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\Clipped\\L8L2A_B4clip1.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\Clipped\\L8L2A_B5clip1.tif'", L8L2A_Stack_tif)

