# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Level2_NDVI_Maize_based_on_third_trial_Level1.py
# Created on: 2020-10-30 17:07:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
LC08_L1TP_191029_20170620_20170630_01_T1_sr_band5_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\LC081910292017062001T1-SC20180223140052\\LC08_L1TP_191029_20170620_20170630_01_T1_sr_band5.tif"
rectangle_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\rectangle.shp"
L8_B5_RectClip_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\RectangleClipped\\L8_B5_RectClip.tif"
LC08_L1TP_191029_20170620_20170630_01_T1_sr_band4_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\LC081910292017062001T1-SC20180223140052\\LC08_L1TP_191029_20170620_20170630_01_T1_sr_band4.tif"
L8_B4_RectClip_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\RectangleClipped\\L8_B4_RectClip.tif"
L8L2_RectClip_NDVI_30m_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\RectangleClipped\\NDVI\\L8L2_RectClip_NDVI_30m.tif"
QQB8AClip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB8AClip1.tif"
QPB04Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB04Clip1.tif"
S2L2_NDVI_RectClip_20m_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\NDVI\\S2L2_NDVI_RectClip_20m.tif"
Maize_within_Eo_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\Maize_within_Eo.shp"
S2L2_NDVI_RectClip__Maize_20m_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\NDVI\\S2L2_NDVI_RectClip__Maize_20m.tif"
griddedpoints_s2L2_maize_20m_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_s2L2_maize_20m.shp"
L8L2_NDVI_Maize = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\RectangleClipped\\NDVI\\L8L2_NDVI_Maize"

# Process: Clip (3)
arcpy.Clip_management(LC08_L1TP_191029_20170620_20170630_01_T1_sr_band5_tif, "241514,694364513 4859043,41602539 330198,804643095 4938392,49105477", L8_B5_RectClip_tif, rectangle_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (2)
arcpy.Clip_management(LC08_L1TP_191029_20170620_20170630_01_T1_sr_band4_tif, "241514,694364513 4859043,41602539 330198,804643095 4938392,49105477", L8_B4_RectClip_tif, rectangle_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(Float(\"%L8_B5_RectClip.tif%\") - Float(\"%L8_B4_RectClip.tif%\")) / (Float(\"%L8_B5_RectClip.tif%\") + Float(\"%L8_B4_RectClip.tif%\"))", L8L2_RectClip_NDVI_30m_tif)

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(Float(\"%QQB8AClip1.tif%\") - Float(\"%QPB04Clip1.tif%\")) / (Float(\"%QQB8AClip1.tif%\") + Float(\"%QPB04Clip1.tif%\"))", S2L2_NDVI_RectClip_20m_tif)

# Process: Clip
arcpy.Clip_management(S2L2_NDVI_RectClip_20m_tif, "731960 4868700 800660 4933666,77474976", S2L2_NDVI_RectClip__Maize_20m_tif, Maize_within_Eo_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster to Point
arcpy.RasterToPoint_conversion(S2L2_NDVI_RectClip__Maize_20m_tif, griddedpoints_s2L2_maize_20m_shp, "Value")

# Process: Sample
arcpy.gp.Sample_sa("'F:\\ArcGIS\\Additional_Thesis\\L2A\\Landsat 8\\RectangleClipped\\NDVI\\L8L2_RectClip_NDVI_30m.tif'", griddedpoints_s2L2_maize_20m_shp, L8L2_NDVI_Maize, "NEAREST", "", "CURRENT_SLICE")

