# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Level_1C_DOS1_NDVI_Maize.py
# Created on: 2020-10-30 17:06:36.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
RT_QP_Mosaic_B08_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\Mosaics\\RT_QP_Mosaic_B08.tif"
RT_QP_Mosaic_B08_tif__3_ = RT_QP_Mosaic_B08_tif
RT_T32TQQ_20170620T100031_B08_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\RT_T32TQQ_20170620T100031_B08.tif"
rectangle_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\rectangle.shp"
QPMosaic_B08_RectClip_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\Mosaics\\RectangleClipped\\QPMosaic_B08_RectClip.tif"
RT_QP_Mosaic_B04_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\Mosaics\\RT_QP_Mosaic_B04.tif"
RT_QP_Mosaic_B04_tif__3_ = RT_QP_Mosaic_B04_tif
RT_T32TQQ_20170620T100031_B04_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\RT_T32TQQ_20170620T100031_B04.tif"
QPMosaic_B04_RectClip_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\Mosaics\\RectangleClipped\\QPMosaic_B04_RectClip.tif"
RT_S2_Mosaic_NDVI_RectClip_10m_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\RT_S2_Mosaic_NDVI_RectClip_10m.tif"
randomPointsMaizeEo_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\randomPointsMaizeEo.shp"
RT_S2_Mosaic_NDVI_RectClip_10m = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\RT_S2_Mosaic_NDVI_RectClip_10m"
RT_LC08_L1TP_191029_20170620_20170630_01_T1_B5_TIF = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\RT_LC08_L1TP_191029_20170620_20170630_01_T1_B5.TIF"
rectangle_shp__2_ = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\rectangle.shp"
L8_B5_RectClip_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\RectangleClip\\L8_B5_RectClip.tif"
RT_LC08_L1TP_191029_20170620_20170630_01_T1_B4_TIF = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\RT_LC08_L1TP_191029_20170620_20170630_01_T1_B4.TIF"
L8_B4_RectClip_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\RectangleClip\\L8_B4_RectClip.tif"
RT_L8_NDVI_RectClip_30m_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\RT_L8_NDVI_RectClip_30m.tif"
randomPointsMaizeEo_L8Projection_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\randomPointsMaizeEo_L8Projection.shp"
RE_L8_NDVI_RectClip_30m = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\RE_L8_NDVI_RectClip_30m"
RT_L8_NDVI_RectClip_30m_tif__2_ = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\NDVI\\RT_L8_NDVI_RectClip_30m.tif"
RT_QP_Mosaic_B8A_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RT_QP_Mosaic_B8A.tif"
RT_QP_Mosaic_B8A_tif__3_ = RT_QP_Mosaic_B8A_tif
RT_T32TQQ_20170620T100031_B8A_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\RT_T32TQQ_20170620T100031_B8A.tif"
rectangle_shp__3_ = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\rectangle.shp"
QPMosaic_B8A_RectClip_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RectangleClipped\\QPMosaic_B8A_RectClip.tif"
QPMosaic_B04_RectClip_tif__2_ = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RectangleClipped\\QPMosaic_B04_RectClip.tif"
Output_Cell_Size = "20 20"
Resampling_Method = "NEAREST"
QPB04Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB04Clip1.tif"
QPMosaic_B04_RectClip_20m_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RectangleClipped\\Resampled 20m\\QPMosaic_B04_RectClip_20m.tif"
RT_S2_Mosaic_NDVI_RectClip_20m_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\NDVI\\RT_S2_Mosaic_NDVI_RectClip_20m.tif"
Maize_within_Eo_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\Maize_within_Eo.shp"
RT_S2_Mosaic_NDVI_RectClip_20m_Maize_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\NDVI\\RT_S2_Mosaic_NDVI_RectClip_20m_Maize.tif"
griddedpoints_s2_maize_20m_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_s2_maize_20m.shp"
l8dos1ndvi_20m = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\NDVI\\l8dos1ndvi_20m"
RT_L8_NDVI_RectClip_30m_tif__3_ = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\NDVI\\RT_L8_NDVI_RectClip_30m.tif"
QPMosaic_B08_RectClip_tif__2_ = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RectangleClipped\\QPMosaic_B08_RectClip.tif"
Output_Cell_Size__2_ = "30 30"
QPMosaic_B08_RectClip_30m_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RectangleClipped\\Resampled 30m\\QPMosaic_B08_RectClip_30m.tif"
QPMosaic_B04_RectClip_tif__3_ = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RectangleClipped\\QPMosaic_B04_RectClip.tif"
QPMosaic_B04_RectClip_30m_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RectangleClipped\\Resampled 30m\\QPMosaic_B04_RectClip_30m.tif"
RT_S2_Mosaic_NDVI_RectClip_30m_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\NDVI\\RT_S2_Mosaic_NDVI_RectClip_30m.tif"
Maize_within_Eo_shp__2_ = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\Maize_within_Eo.shp"
RT_S2_Mosaic_NDVI_RectClip_30m_Maize_tif = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\NDVI\\RT_S2_Mosaic_NDVI_RectClip_30m_Maize.tif"
griddedpoints_s2_maize_30m_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\griddedpoints_s2_maize_30m.shp"
l8dos1ndvi_30m = "F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\NDVI\\l8dos1ndvi_30m"

# Process: Mosaic (2)
arcpy.Mosaic_management("'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\Mosaics\\RT_QP_Mosaic_B08.tif';'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\RT_T32TQQ_20170620T100031_B08.tif'", RT_QP_Mosaic_B08_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Clip (2)
arcpy.Clip_management(RT_QP_Mosaic_B08_tif__3_, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QPMosaic_B08_RectClip_tif, rectangle_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Mosaic
arcpy.Mosaic_management("'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\Mosaics\\RT_QP_Mosaic_B04.tif';'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\RT_T32TQQ_20170620T100031_B04.tif'", RT_QP_Mosaic_B04_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Clip
arcpy.Clip_management(RT_QP_Mosaic_B04_tif__3_, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QPMosaic_B04_RectClip_tif, rectangle_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(Float(\"%QPMosaic_B08_RectClip.tif%\") - Float(\"%QPMosaic_B04_RectClip.tif%\")) / (Float(\"%QPMosaic_B08_RectClip.tif%\") + Float(\"%QPMosaic_B04_RectClip.tif%\"))", RT_S2_Mosaic_NDVI_RectClip_10m_tif)

# Process: Sample
arcpy.gp.Sample_sa("'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\Dos1 correction\\RT_S2_Mosaic_NDVI_RectClip_10m.tif'", randomPointsMaizeEo_shp, RT_S2_Mosaic_NDVI_RectClip_10m, "NEAREST", "", "CURRENT_SLICE")

# Process: Clip (4)
arcpy.Clip_management(RT_LC08_L1TP_191029_20170620_20170630_01_T1_B5_TIF, "241514,694364513 4859043,41602539 330198,804643095 4938392,49105477", L8_B5_RectClip_tif, rectangle_shp__2_, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (3)
arcpy.Clip_management(RT_LC08_L1TP_191029_20170620_20170630_01_T1_B4_TIF, "241514,694364513 4859043,41602539 330198,804643095 4938392,49105477", L8_B4_RectClip_tif, rectangle_shp__2_, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(Float(\"%L8_B5_RectClip.tif%\") - Float(\"%L8_B4_RectClip.tif%\")) / (Float(\"%L8_B5_RectClip.tif%\") + Float(\"%L8_B4_RectClip.tif%\"))", RT_L8_NDVI_RectClip_30m_tif)

# Process: Sample (2)
arcpy.gp.Sample_sa("'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\RT_L8_NDVI_RectClip_30m.tif'", randomPointsMaizeEo_L8Projection_shp, RE_L8_NDVI_RectClip_30m, "NEAREST", "", "CURRENT_SLICE")

# Process: Mosaic (3)
arcpy.Mosaic_management("'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\Mosaics\\RT_QP_Mosaic_B8A.tif';'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Sentinel 2\\DOS1 correction\\RT_T32TQQ_20170620T100031_B8A.tif'", RT_QP_Mosaic_B8A_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Clip (5)
arcpy.Clip_management(RT_QP_Mosaic_B8A_tif__3_, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QPMosaic_B8A_RectClip_tif, rectangle_shp__3_, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Resample
tempEnvironment0 = arcpy.env.resamplingMethod
arcpy.env.resamplingMethod = Resampling Method
tempEnvironment1 = arcpy.env.snapRaster
arcpy.env.snapRaster = QPB04Clip1.tif
arcpy.Resample_management(QPMosaic_B04_RectClip_tif__2_, QPMosaic_B04_RectClip_20m_tif, Output_Cell_Size, "NEAREST")
arcpy.env.resamplingMethod = tempEnvironment0
arcpy.env.snapRaster = tempEnvironment1

# Process: Raster Calculator (3)
arcpy.gp.RasterCalculator_sa("(Float(\"%QPMosaic_B8A_RectClip.tif%\") - Float(\"%QPMosaic_B04_RectClip_20m.tif%\")) / (Float(\"%QPMosaic_B8A_RectClip.tif%\") + Float(\"%QPMosaic_B04_RectClip_20m.tif%\"))", RT_S2_Mosaic_NDVI_RectClip_20m_tif)

# Process: Clip (6)
arcpy.Clip_management(RT_S2_Mosaic_NDVI_RectClip_20m_tif, "731960 4868700 800660 4933666,77474976", RT_S2_Mosaic_NDVI_RectClip_20m_Maize_tif, Maize_within_Eo_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster to Point
arcpy.RasterToPoint_conversion(RT_S2_Mosaic_NDVI_RectClip_20m_Maize_tif, griddedpoints_s2_maize_20m_shp, "Value")

# Process: Sample (3)
arcpy.gp.Sample_sa("'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\NDVI\\RT_L8_NDVI_RectClip_30m.tif'", griddedpoints_s2_maize_20m_shp, l8dos1ndvi_20m, "NEAREST", "", "CURRENT_SLICE")

# Process: Resample (3)
arcpy.Resample_management(QPMosaic_B08_RectClip_tif__2_, QPMosaic_B08_RectClip_30m_tif, Output_Cell_Size__2_, "NEAREST")

# Process: Resample (2)
arcpy.Resample_management(QPMosaic_B04_RectClip_tif__3_, QPMosaic_B04_RectClip_30m_tif, Output_Cell_Size__2_, "NEAREST")

# Process: Raster Calculator (4)
arcpy.gp.RasterCalculator_sa("(Float(\"%QPMosaic_B08_RectClip_30m.tif%\") - Float(\"%QPMosaic_B04_RectClip_30m.tif%\")) / (Float(\"%QPMosaic_B08_RectClip_30m.tif%\") + Float(\"%QPMosaic_B04_RectClip_30m.tif%\"))", RT_S2_Mosaic_NDVI_RectClip_30m_tif)

# Process: Clip (7)
arcpy.Clip_management(RT_S2_Mosaic_NDVI_RectClip_30m_tif, "731960 4868700 800660 4933666,77474976", RT_S2_Mosaic_NDVI_RectClip_30m_Maize_tif, Maize_within_Eo_shp__2_, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster to Point (2)
arcpy.RasterToPoint_conversion(RT_S2_Mosaic_NDVI_RectClip_30m_Maize_tif, griddedpoints_s2_maize_30m_shp, "Value")

# Process: Sample (4)
arcpy.gp.Sample_sa("'F:\\ArcGIS\\Additional_Thesis\\Level 1C\\Landsat 8\\DOS1 correction\\NDVI\\RT_L8_NDVI_RectClip_30m.tif'", griddedpoints_s2_maize_30m_shp, l8dos1ndvi_30m, "NEAREST", "", "CURRENT_SLICE")

