# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Model.py
# Created on: 2020-10-30 17:07:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
S2A_Mosaic_BareSoilIndex_iCOR_10m_Clip_col_tif = "S2A_Mosaic_BareSoilIndex_iCOR_10m_Clip_col.tif"
CSI_LC08_DeltaCorrected_tif = "CSI_LC08_DeltaCorrected.tif"
CSI_LC08_DeltaCorrected_bsi_tif = "F:\\ArcGIS\\Additional_Thesis\\Miscellaneous\\CSI_LC08_DeltaCorrected_bsi.tif"
Maize_within_Eo_L8CRS_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\Maize_within_Eo_L8CRS.shp"
CSI_LC08_DeltaCorrected_bsi_maize_tif = "F:\\ArcGIS\\Additional_Thesis\\Miscellaneous\\CSI_LC08_DeltaCorrected_bsi_maize.tif"
LC08_Kc_iCOR_3_Clip_tif = "LC08_Kc_iCOR_3_Clip.tif"
LC08_Kc_iCOR_3_Clip_bsi_tif = "F:\\SNAP\\iCOR\\Landsat 8\\LC08_Kc_iCOR_3_Clip_bsi.tif"
LC08_Kc_iCOR_3_Clip_bsi_maize_tif = "F:\\SNAP\\iCOR\\Landsat 8\\LC08_Kc_iCOR_3_Clip_bsi_maize.tif"
S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip_tif = "S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip.tif"
S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip_bsi_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2REP\\S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip_bsi.tif"
S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip_bsi_maize_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2REP\\S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip_bsi_maize.tif"
S2A_Mosaic_Kc_iCOR_30m_Clip_tif = "S2A_Mosaic_Kc_iCOR_30m_Clip.tif"
S2A_Mosaic_Kc_iCOR_30m_Clip_bsi_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2A_Mosaic_Kc_iCOR_30m_Clip_bsi.tif"
S2A_Mosaic_Kc_iCOR_30m_Clip_bsi_maize_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2A_Mosaic_Kc_iCOR_30m_Clip_bsi_maize.tif"

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("Con(\"%S2A_Mosaic_BareSoilIndex_iCOR_10m_Clip_col.tif%\" < -0.15, \"%CSI_LC08_DeltaCorrected.tif%\")", CSI_LC08_DeltaCorrected_bsi_tif)

# Process: Clip
arcpy.Clip_management(CSI_LC08_DeltaCorrected_bsi_tif, "252883,672118938 4864945,54287185 319198,220048529 4932464,52581433", CSI_LC08_DeltaCorrected_bsi_maize_tif, Maize_within_Eo_L8CRS_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("Con(\"%S2A_Mosaic_BareSoilIndex_iCOR_10m_Clip_col.tif%\" < -0.15,\"%LC08_Kc_iCOR_3_Clip.tif%\")", LC08_Kc_iCOR_3_Clip_bsi_tif)

# Process: Clip (2)
arcpy.Clip_management(LC08_Kc_iCOR_3_Clip_bsi_tif, "252883,672118938 4864945,54287185 319198,220048529 4932464,52581433", LC08_Kc_iCOR_3_Clip_bsi_maize_tif, Maize_within_Eo_L8CRS_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster Calculator (3)
arcpy.gp.RasterCalculator_sa("Con(\"%S2A_Mosaic_BareSoilIndex_iCOR_10m_Clip_col.tif%\" < -0.15,\"%S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip.tif%\")", S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip_bsi_tif)

# Process: Clip (3)
arcpy.Clip_management(S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip_bsi_tif, "252883,672118938 4864945,54287185 319198,220048529 4932464,52581433", S2A_Mosaic_S2REP_iCOR_30m_collocate_Clip_bsi_maize_tif, Maize_within_Eo_L8CRS_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster Calculator (4)
arcpy.gp.RasterCalculator_sa("Con(\"%S2A_Mosaic_BareSoilIndex_iCOR_10m_Clip_col.tif%\" < -0.15,\"%S2A_Mosaic_Kc_iCOR_30m_Clip.tif%\")", S2A_Mosaic_Kc_iCOR_30m_Clip_bsi_tif)

# Process: Clip (4)
arcpy.Clip_management(S2A_Mosaic_Kc_iCOR_30m_Clip_bsi_tif, "252883,672118938 4864945,54287185 319198,220048529 4932464,52581433", S2A_Mosaic_Kc_iCOR_30m_Clip_bsi_maize_tif, Maize_within_Eo_L8CRS_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

