# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Quality_Data_Clip.py
# Created on: 2020-10-30 17:07:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
L2A_T32TQP_20170620T100031_SCL_20m_jp2 = "F:\\TU Delft\\Additional_Thesis\\Data\\Level 2A Products\\Sentinel-2A\\S2A_MSIL2A_20170620T100031_N0205_R122_T32TQP_20170620T100453.SAFE\\GRANULE\\L2A_T32TQP_A010415_20170620T100453\\IMG_DATA\\R20m\\L2A_T32TQP_20170620T100031_SCL_20m.jp2"
et0pm_polygDiss_shp = "F:\\ArcGIS\\Additional_Thesis\\AreaOfInterest\\et0pm_polygDiss.shp"
QP_SCL_clip_tif = "F:\\ArcGIS\\Additional_Thesis\\Quality outputs\\S2\\QP_SCL_clip.tif"
L2A_T32TQQ_20170620T100031_SCL_20m_jp2 = "F:\\TU Delft\\Additional_Thesis\\Data\\Level 2A Products\\Sentinel-2A\\S2A_MSIL2A_20170620T100031_N0205_R122_T32TQQ_20170620T100453.SAFE\\GRANULE\\L2A_T32TQQ_A010415_20170620T100453\\IMG_DATA\\R20m\\L2A_T32TQQ_20170620T100031_SCL_20m.jp2"
QQ_SCL_clip_tif = "F:\\ArcGIS\\Additional_Thesis\\Quality outputs\\S2\\QQ_SCL_clip.tif"

# Process: Clip
arcpy.Clip_management(L2A_T32TQP_20170620T100031_SCL_20m_jp2, "731316,168484007 4867605,18488819 800766,168484008 4934565,18488819", QP_SCL_clip_tif, et0pm_polygDiss_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (2)
arcpy.Clip_management(L2A_T32TQQ_20170620T100031_SCL_20m_jp2, "731316,168484007 4867605,18488819 800766,168484008 4934565,18488819", QQ_SCL_clip_tif, et0pm_polygDiss_shp, "255", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

