# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# S2_L2A_S2REP.py
# Created on: 2020-10-30 17:08:40.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
L2A_T32TQP_20170620T100031_B04_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QP\\L2A_T32TQP_20170620T100031_B04_20m.jp2"
rectangle_shp = "F:\\ArcGIS\\Additional_Thesis\\AreaOfInterest\\rectangle.shp"
QPB04Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB04Clip1.tif"
QPB04Clip1_tif__3_ = QPB04Clip1_tif
L2A_T32TQQ_20170620T100031_B04_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QQ\\L2A_T32TQQ_20170620T100031_B04_20m.jp2"
QQB04Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB04Clip1.tif"
et0pm_polygDiss_shp = "F:\\ArcGIS\\Additional_Thesis\\AreaOfInterest\\et0pm_polygDiss.shp"
QPB04Clip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB04Clip2.tif"
L2A_T32TQP_20170620T100031_B05_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QP\\L2A_T32TQP_20170620T100031_B05_20m.jp2"
QPB05Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB05Clip1.tif"
QPB05Clip1_tif__3_ = QPB05Clip1_tif
L2A_T32TQQ_20170620T100031_B05_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QQ\\L2A_T32TQQ_20170620T100031_B05_20m.jp2"
QQB05Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB05Clip1.tif"
QPB05Clip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB05Clip2.tif"
L2A_T32TQQ_20170620T100031_B06_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QQ\\L2A_T32TQQ_20170620T100031_B06_20m.jp2"
QQB06Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB06Clip1.tif"
QPB06Clip1_tif__3_ = QQB06Clip1_tif
L2A_T32TQP_20170620T100031_B06_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QP\\L2A_T32TQP_20170620T100031_B06_20m.jp2"
QPB06Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB06Clip1.tif"
QPB06Clip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB06Clip2.tif"
L2A_T32TQP_20170620T100031_B07_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QP\\L2A_T32TQP_20170620T100031_B07_20m.jp2"
QPB07Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB07Clip1.tif"
QPB07Clip1_tif__3_ = QPB07Clip1_tif
L2A_T32TQQ_20170620T100031_B07_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QQ\\L2A_T32TQQ_20170620T100031_B07_20m.jp2"
QQB07Clip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB07Clip1.tif"
QPB07Clip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB07Clip2.tif"
L2A_T32TQP_20170620T100031_B8A_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QP\\L2A_T32TQP_20170620T100031_B8A_20m.jp2"
QPB8AClip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB8AClip1.tif"
QPB8AClip1_tif__3_ = QPB8AClip1_tif
L2A_T32TQQ_20170620T100031_B8A_20m_jp2 = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\QQ\\L2A_T32TQQ_20170620T100031_B8A_20m.jp2"
QQB8AClip1_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB8AClip1.tif"
QPB8AClip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB8AClip2.tif"
S220mstackClip_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\S220mstackClip.tif"

# Process: Clip (4)
arcpy.Clip_management(L2A_T32TQP_20170620T100031_B04_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QPB04Clip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (5)
arcpy.Clip_management(L2A_T32TQQ_20170620T100031_B04_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QQB04Clip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Mosaic (4)
arcpy.Mosaic_management("'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB04Clip1.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB04Clip1.tif'", QPB04Clip1_tif, "LAST", "FIRST", "", "0", "NONE", "0", "NONE")

# Process: Clip (12)
arcpy.Clip_management(QPB04Clip1_tif__3_, "731316,168484007 4867605,18488819 800766,168484008 4934565,18488819", QPB04Clip2_tif, et0pm_polygDiss_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (3)
arcpy.Clip_management(L2A_T32TQP_20170620T100031_B05_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QPB05Clip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (6)
arcpy.Clip_management(L2A_T32TQQ_20170620T100031_B05_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QQB05Clip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Mosaic (3)
arcpy.Mosaic_management("'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB05Clip1.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB05Clip1.tif'", QPB05Clip1_tif, "LAST", "FIRST", "", "0", "NONE", "0", "NONE")

# Process: Clip (11)
arcpy.Clip_management(QPB05Clip1_tif__3_, "731316,168484007 4867605,18488819 800766,168484008 4934565,18488819", QPB05Clip2_tif, et0pm_polygDiss_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (7)
arcpy.Clip_management(L2A_T32TQQ_20170620T100031_B06_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QQB06Clip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (2)
arcpy.Clip_management(L2A_T32TQP_20170620T100031_B06_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QPB06Clip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Mosaic (2)
arcpy.Mosaic_management("'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB06Clip1.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB06Clip1.tif'", QPB06Clip1_tif, "LAST", "FIRST", "", "0", "NONE", "0", "NONE")

# Process: Clip (10)
arcpy.Clip_management(QPB06Clip1_tif__3_, "731316,168484007 4867605,18488819 800766,168484008 4934565,18488819", QPB06Clip2_tif, et0pm_polygDiss_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip
arcpy.Clip_management(L2A_T32TQP_20170620T100031_B07_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QPB07Clip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (8)
arcpy.Clip_management(L2A_T32TQQ_20170620T100031_B07_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QQB07Clip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Mosaic
arcpy.Mosaic_management("'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB07Clip1.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB07Clip1.tif'", QPB07Clip1_tif, "LAST", "FIRST", "", "0", "NONE", "0", "NONE")

# Process: Clip (9)
arcpy.Clip_management(QPB07Clip1_tif__3_, "731316,168484007 4867605,18488819 800766,168484008 4934565,18488819", QPB07Clip2_tif, et0pm_polygDiss_shp, "0", "NONE", "NO_MAINTAIN_EXTENT")

# Process: Clip (13)
arcpy.Clip_management(L2A_T32TQP_20170620T100031_B8A_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QPB8AClip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Clip (14)
arcpy.Clip_management(L2A_T32TQQ_20170620T100031_B8A_20m_jp2, "723426,097038214 4863831,6003664 806997,156311637 4937300,66346392", QQB8AClip1_tif, rectangle_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Mosaic (5)
arcpy.Mosaic_management("'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QPB8AClip1.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Clipped\\QQB8AClip1.tif'", QPB8AClip1_tif, "LAST", "FIRST", "", "0", "NONE", "0", "NONE")

# Process: Clip (15)
arcpy.Clip_management(QPB8AClip1_tif__3_, "731316,168484007 4867605,18488819 800766,168484008 4934565,18488819", QPB8AClip2_tif, et0pm_polygDiss_shp, "0", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Composite Bands
arcpy.CompositeBands_management("'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB04Clip2.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB05Clip2.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB06Clip2.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB07Clip2.tif';'F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB8AClip2.tif'", S220mstackClip_tif)

