# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Sentinel_2_iCOR_S2REP_CWR.py
# Created on: 2020-10-30 17:09:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Band_1 = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_20M.tif\\Band_1"
S2A_QP_B5_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QP_B5_iCOR_20m.tif"
S2A_Mosaic_B05_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B05_iCOR_20m.tif"
S2A_Mosaic_B05_iCOR_20m_tif__2_ = S2A_Mosaic_B05_iCOR_20m_tif
Band_1__2_ = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_20M.tif\\Band_1"
S2A_QQ_B5_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QQ_B5_iCOR_20m.tif"
Band_2 = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_20M.tif\\Band_2"
S2A_QP_B6_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QP_B6_iCOR_20m.tif"
S2A_Mosaic_B06_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B06_iCOR_20m.tif"
S2A_Mosaic_B06_iCOR_20m_tif__2_ = S2A_Mosaic_B06_iCOR_20m_tif
Band_2__2_ = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_20M.tif\\Band_2"
S2A_QQ_B6_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QQ_B6_iCOR_20m.tif"
Band_3 = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_20M.tif\\Band_3"
S2A_QP_B7_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QP_B7_iCOR_20m.tif"
S2A_Mosaic_B07_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B07_iCOR_20m.tif"
S2A_Mosaic_B07_iCOR_20m_tif__2_ = S2A_Mosaic_B07_iCOR_20m_tif
Band_3__2_ = "F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_20M.tif\\Band_3"
S2A_QQ_B7_iCOR_20m_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QQ_B7_iCOR_20m.tif"
S2A_Mosaic_B07_iCOR_30m_collocate_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2A_Mosaic_B07_iCOR_30m_collocate.tif"
S2A_Mosaic_B04_iCOR_30m_collocate2_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2A_Mosaic_B04_iCOR_30m_collocate2.tif"
S2A_Mosaic_B05_iCOR_30m_collocate_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2A_Mosaic_B05_iCOR_30m_collocate.tif"
S2A_Mosaic_B06_iCOR_30m_collocate_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2A_Mosaic_B06_iCOR_30m_collocate.tif"
S2A_Mosaic_S2REP_iCOR_30m_collocate_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\S2REP\\S2A_Mosaic_S2REP_iCOR_30m_collocate.tif"
S2A_Mosaic_NDVI_iCOR_30m_collocate_tif__2_ = "S2A_Mosaic_NDVI_iCOR_30m_collocate.tif"
ET0pm_30m_tif = "F:\\ArcGIS\\Additional_Thesis\\Silvia_MOSES_NDVI\\Kostas_share_2\\20_06_2017\\METEO\\ET0pm_30m.tif"
S2A_CWR_emp_iCOR_30m_collocate_tif = "F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\Collocate to L8\\CWR\\S2A_CWR_emp_iCOR_30m_collocate.tif"

# Process: Composite Bands
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_20M.tif\\Band_1'", S2A_QP_B5_iCOR_20m_tif)

# Process: Copy Raster
arcpy.CopyRaster_management(S2A_QP_B5_iCOR_20m_tif, S2A_Mosaic_B05_iCOR_20m_tif, "", "", "", "NONE", "NONE", "", "NONE", "NONE", "", "NONE")

# Process: Composite Bands (4)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_20M.tif\\Band_1'", S2A_QQ_B5_iCOR_20m_tif)

# Process: Mosaic
arcpy.Mosaic_management("'F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B05_iCOR_20m.tif';'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QQ_B5_iCOR_20m.tif'", S2A_Mosaic_B05_iCOR_20m_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Composite Bands (2)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_20M.tif\\Band_2'", S2A_QP_B6_iCOR_20m_tif)

# Process: Copy Raster (2)
arcpy.CopyRaster_management(S2A_QP_B6_iCOR_20m_tif, S2A_Mosaic_B06_iCOR_20m_tif, "", "", "", "NONE", "NONE", "", "NONE", "NONE", "", "NONE")

# Process: Composite Bands (5)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_20M.tif\\Band_2'", S2A_QQ_B6_iCOR_20m_tif)

# Process: Mosaic (2)
arcpy.Mosaic_management("'F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B06_iCOR_20m.tif';'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QQ_B6_iCOR_20m.tif'", S2A_Mosaic_B06_iCOR_20m_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Composite Bands (3)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQP_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQP_N02_05_20M.tif\\Band_3'", S2A_QP_B7_iCOR_20m_tif)

# Process: Copy Raster (3)
arcpy.CopyRaster_management(S2A_QP_B7_iCOR_20m_tif, S2A_Mosaic_B07_iCOR_20m_tif, "", "", "", "NONE", "NONE", "", "NONE", "NONE", "", "NONE")

# Process: Composite Bands (6)
arcpy.CompositeBands_management("'F:\\SNAP\\iCOR\\Sentinel 2\\QQ\\S2A_MSIL1C_20170620T100031_N0205_R122_T32TQQ_20170620T100453_iCOR_S2A_OPER_MSI_L1C_TL_SGS__20170620T152200_A010415_T32TQQ_N02_05_20M.tif\\Band_3'", S2A_QQ_B7_iCOR_20m_tif)

# Process: Mosaic (3)
arcpy.Mosaic_management("'F:\\SNAP\\iCOR\\Sentinel 2\\Mosaic\\S2A_Mosaic_B07_iCOR_20m.tif';'F:\\SNAP\\iCOR\\Sentinel 2\\QP\\S2A_QQ_B7_iCOR_20m.tif'", S2A_Mosaic_B07_iCOR_20m_tif, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("705 + 35*(0.5 * (\"%S2A_Mosaic_B07_iCOR_30m_collocate.tif%\" +\"%S2A_Mosaic_B04_iCOR_30m_collocate2.tif%\") - \"%S2A_Mosaic_B05_iCOR_30m_collocate.tif%\")/(\"%S2A_Mosaic_B06_iCOR_30m_collocate.tif%\" - \"%S2A_Mosaic_B05_iCOR_30m_collocate.tif%\")", S2A_Mosaic_S2REP_iCOR_30m_collocate_tif)

# Process: Raster Calculator (2)
tempEnvironment0 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = "PROJCS['WGS_1984_UTM_Zone_33N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',15.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]"
tempEnvironment1 = arcpy.env.resamplingMethod
arcpy.env.resamplingMethod = "NEAREST"
tempEnvironment2 = arcpy.env.snapRaster
arcpy.env.snapRaster = "S2A_Mosaic_NDVI_iCOR_30m_collocate.tif"
tempEnvironment3 = arcpy.env.cellSize
arcpy.env.cellSize = "30"
arcpy.gp.RasterCalculator_sa("(\"%S2A_Mosaic_NDVI_iCOR_30m_collocate.tif (2)%\" * 1.25 + 0.2) * \"%ET0pm_30m.tif%\"", S2A_CWR_emp_iCOR_30m_collocate_tif)
arcpy.env.outputCoordinateSystem = tempEnvironment0
arcpy.env.resamplingMethod = tempEnvironment1
arcpy.env.snapRaster = tempEnvironment2
arcpy.env.cellSize = tempEnvironment3

