# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Sentinel2_final.py
# Created on: 2020-10-30 17:09:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
QPB8AClip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB8AClip2.tif"
QPB04Clip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB04Clip2.tif"
S2_ndvi = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\S2_NDVI\\s2_ndvi"
Maize_within_Eo_shp = "F:\\ArcGIS\\Additional_Thesis\\Geometries\\Maize_within_Eo.shp"
S2_ndvi_Maize_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\S2_NDVI\\S2_ndvi_Maize.tif"
QPB07Clip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB07Clip2.tif"
QPB05Clip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB05Clip2.tif"
QPB06Clip2_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\QPB06Clip2.tif"
S2REP_tif = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\S2REP\\S2REP.tif"
S2REP_Maize_tif__2_ = "F:\\ArcGIS\\Additional_Thesis\\L2A\\Sentinel 2\\Mosaic\\S2REP\\S2REP_Maize.tif"

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(Float(\"%QPB8AClip2.tif%\") - Float(\"%QPB04Clip2.tif%\"))/(Float(\"%QPB8AClip2.tif%\") + Float(\"%QPB04Clip2.tif%\"))", S2_ndvi)

# Process: Clip
arcpy.Clip_management(S2_ndvi, "731960 4868700 800660 4933666,77474976", S2_ndvi_Maize_tif, Maize_within_Eo_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("705 + 35*(0.5 * (Float(\"%QPB07Clip2.tif%\") * 0.0001 + Float(\"%QPB04Clip2.tif%\") * 0.0001) - Float(\"%QPB05Clip2.tif%\") * 0.0001)/(Float(\"%QPB06Clip2.tif%\")*0.0001 - Float(\"%QPB05Clip2.tif%\")*0.0001)", S2REP_tif)

# Process: Clip (2)
arcpy.Clip_management(S2REP_tif, "731960 4868700 800660 4933666,77474976", S2REP_Maize_tif__2_, Maize_within_Eo_shp, "", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

